language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - neigmer_14@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: e7xCabDESpDfYaex1LJNrt3h+IK+oIM3sGkFOZECet8nQwhK67FIFGoVST1WxZ58SUc5Wj+0nJNuxLHKr7RkypW2Pi3sP0CVA1dnAmjVyJy8bs0JgakP0lO9U85G1K2oPOY7Ayt5szbHfEfisIEClenI5yQ4DErZ56sFv7ehaVHI5Qmh69iK6QjKJ7vVW5d6GJD3HmDsnEmgR7MoT3RgK+wbI8bIf6a365zVgMKy7tBnn1Zs7J3i2pFVTkZtJvqnlj/R50oOZGF2C1xZ7UvD2X6Lg0lU78CT5zE+EYSt4tMnZ8cKv2lvySP6ntdTPrJQB36K5te6gUMc492DWmxjp4enrrKmSVQwZiEVe78yb8b2OcoS3Vpy6EOvmJcEfJH9GF+A6S1v0Tw0PoQ5o6VIOBjN8rs1nzSqoWvs9MMNcKNURYewpVOEbdr0XJjBiYNfwH8G/PrEGm+DuVLjOD75X2KztMYbwfyGZw+xd5PTqDOg3yqI/wsam3LFzZRCF6Yf5uDrn0VxREinxBg3AtUgNimxeYSQePzdK/08HXc/SrwmxpTv0WYsixMAwav4waUaSlhyUWH62pOIjZLU8LNFPB8smXZ9BfMsbowkQG4lTFmlX0EYesOGJLjcNgkVOrsinarE8Cf9rTlyHa+htT1i7mz/d0Qhd3na8KQ3LcZNOGU=
  app: prueba-egc159
  on:
    repo: rogur04/bye-java
