language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - neigmer_14@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: p99UmS08WKmROCLbK1hJrnGMzDtJVre8Tnxjq2ucy1BDFbdtCClwTeVphM0woTp/2SVc3Iv1anOlQBerArsnYoGNQNquWDrJ75fDa8f4hZyTmy+3b67Fm86DROgjDFuWjNZ6tjUMR3ya/RlYP3o2enAkC3u0AiXQhiM9eKrBgUkCTXm1/1XHx4p8z5ds56DDyNv+E8mRXDNKoDSAfgVpWmGzPbxCUZAsiLaNkt+MmqD1UU4l4+yD12pH9Q45a3XByFsfeB5ZHuYbWHebnOR1hdcJ/2NoWNYwJl+XaLGFTTJKUmcWrp5AqUR5iy66BSjLLVnVObhW+1HyzmCIJyyk1I8EPh+vjyHIjDpfaldWXXU3EiFG0WoR2amREcBY+bNtKOJAuwPV7ayZVZoUBnji+7UTTjNVUBiaoZexkzbcMABv384L3tinHvxD8NNlTQDECZCuO2sG2lvsaM8ZZrQKMfnXrrGKHDem29oehudYigC+ipmkPV1EiHsEefttES0yQwys8hsgparvPZz2DfgKS0YQYCsxjcy1wInV0L8lthf5oheaiSfRm9WnelSaDmcq8Luh8ztWEQtp7suDWQa/LfHVkYmiyM55KWRTHgwMciCHwyAvjA8cv9JucXhC36ZWq+jFBFw517qlW8b4zMzHUUTnXApo5d68tzje5dkXp1E=
  app: bye-java
  on:
    repo: rogur04/bye-java
