language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - neigmer_14@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: hW7tuGg1+SN/0g3wPVEcNJQUUyi4j2wviblXeV7vibp1zXSaKPMTTHYqqs3Z8C8SADCT+ZiTDsXs05zWvWrkS2Y9M7ZHEc2gmOcSQ0acDo0ZcNISW7FNh8rAczBvmywE4NrEs4snfScd9Wo8olYd2XqeNnydloUHkDQc7qJtNEGNZMM7a8lbEijbhqsWrbyd/LO9fFdxqE6AU1h7XUA9g3QSuL2mhhPNi/UVQkBnw8zIWl0/jG7HZk0Y65oF2736js7sPvF5expzvLBU/VRVty9Lc1p+4fj79XWAOTAaX01eqVWlWmK2exM3RBiNq2Bb8WTCG36vgOHCyzgfV9LTHLkUnWUYovTdPToN857CBdklJ/REeVTh8HOAv3fWaBIUFPNgDMtGVDDN8NHI4gygNRUgRdHko1ky3tkZuMG5qzzbiDd5avLuc/2jNfD8MNwhdqFjGNXUF7bR5L7S0T0uX6frratH2urJm+mK78383auxhFS0UB6Vu+DGtQ61aQYGddjElXxD+RGzjjgONYdLqbUCHc9MO216W2/eJcv35mj5wNgQtltF3neEJIWYOQWWzISnU6JGDZmPy1QhcLBCdxmMOZZALZ+5H/WYcUxB8Q7eaPl3hQZTekYmKfWkYDU8sQF2yZf0n7zUcwUOY5zC29fPljaUlKwGGiUwUsckFQU=
  app: bye-java
  on:
    repo: rogur04/bye-java
