language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - neigmer_14@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: FD2spVrffFAhEnQ/W9uTYqpvRcq8BMI3oQhSGxbNjPIzIsZj6+uRcl7T2p8UFCuaYswbI+pyTom08mo5LjhAWQYNfEc8QQ6pdU0Glhvk0afwQndUMH79VB+bCHUXaMxN6NnGQ+qxfzGTaP/hYCalqk+N4CuOHd3xsaF/2OoEn9AY51otICw8SBZbi9TUrdQVuZHveHdAuyWrGBv4j8BDfgVDuTDX6TkdZz39FyJSYGbiRQ3k6WDtEsb77QwwJHWYv6uri3dHpya3H8J0MG44cjirlhSd5gLF6mneugXM68H5sSn8wcf9Y76ryZ+tIfDaICEfVBO6QFhQ5J2TMiX5cixKwyvgvXLKfvOYlwIc/Vc6u4U7gB3808Po/xTbWBae08hmlpNtXR6H7dPQVATug0SQIWTINUMKVRMUrwEMzxWzD95YjkjNGLkAJCem5zj+q/ikpMOJPpx1kC4kqlyxUjL+mwI+pZKIKv7E9YLyLibYAUrrZuQ0xdUngfAarxhNlu8I7+Tw0WJU2ExfbuOSFLYZLQpZcPSOXyxs1oKsidozoquwHS8Qq7X3WYCyd3wPa3n85fV8IThBXo5lhMHhMRLtI1gVRsXZxd/eYwaeHNCZW7hgr42QO1otm7wkQp5A1HQsylTbqIDUwwliMFn/RXUokhRryYor93amoKlrDqU=
  app: bye-java
  on:
    repo: rogur04/bye-java
